config/routes.rb
Blocitoff::Application.routes.draw do



  get "welcome/index"

  devise_for :users

resources :todos, only: [:new, :create, :show, :index, :destroy]  #When we run rake routes, seven route destinations (4th column) are listed. However, we only want these three to show up. 

root to: 'welcome#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :description, :user_id
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :todos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def new
    @todo = Todo.new
  end

  def create
    @todo = current_user.todos.build(params[:todo])
    if @todo.save
    redirect_to @todo, notice: 'Your new TODO was saved'
    end
  end

  def show
    @todo = Todo.find params[:id]
  end

  def index
    @todos = current_user.todos
  end

  def destroy
    @todo = Todo.find params[:id]
    name = @todo.description

    # authorize @todo
    if @todo.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to todos_path
    else
      flash[:error] = "There was an error deleting the todo."
      render :show
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @todo_count = Todo.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p><%= flash[:notice] if flash[:notice] %></p>
    <p><%= flash[:alert] if flash[:alert] %></p>


<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
Total todos = <%= @todos.size %>

<h1>My Todo Items</h1>


<div class="container-fluid">
<div class="row">
  <div class="col-md-8">
    <table class="table">
      <thead>
        <tr>
          <th>Todo Item</th>
          <th>Days Left</th>
          <th>Mark Complete</th>
        </tr>
      </thead>
      <tbody>
        
          <% @todos.each do |todo| %>
            <tr>
              <td><%= todo.description %></td>

              <td><%created = (Date.today - todo.created_at.to_date).to_i

              time_left = (6 - created)%>

              <%=time_left%></td>
              
              <td>
              <%= link_to "Completed", todo, method: :delete, class: 'btn btn-danger', confirm: 'Are you sure you want to complete?' %> 
              </td>

            </tr>
          <% end %>

      </tbody>
    </table>

    <br/>

    <%= link_to "Create New Todo", new_todo_path, class: 'btn btn-large btn-block' %>
  </div>
</div>
</div>


<br/>

app/views/todos/new.html.erb
<%= form_for @todo do |form| %>
  <%= form.text_field :description, placeholder: 'Description' %>
  <%= form.submit 'Save' %>
<% end %>

app/views/todos/show.html.erb
<p><b><%= @todo.description %></b></p>

app/views/welcome/index.html.erb
<h3> Helpful Links</H3>

<div id="user_nav">

    <% if user_signed_in? %>
        Signed in as <%= current_user.email %>
        <li><%= link_to "Sign out", destroy_user_session_path , :method => :delete%></li>
    <% else %>
        <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
    <% end %>
</div>